import { openmrsClient } from '../../config/openmrs-client';
import { config } from '../../config/env';
import {
  OpenMRSPatient,
  OpenMRSListResponse,
  CreatePatientPayload,
} from '../../common/types/openmrs.types';

export interface CreatePatientInput {
  givenName:   string;
  familyName:  string;
  gender:      'M' | 'F';
  birthdate?:  string;
  age?:        number;
  identifier:  string;
}

const IDGEN_SOURCE_UUID = '8549f706-7e85-4c1d-9424-217d50a2988b';
const OPENMRS_ID_TYPE   = '05a29f94-c0ed-11e2-94be-8c13b969e334';

export class PatientService {
  async searchPatients(query: string): Promise<OpenMRSPatient[]> {
    if (!query || query.trim().length < 2) {
      throw new Error('Search query must be at least 2 characters');
    }
    const response = await openmrsClient.get<OpenMRSListResponse<OpenMRSPatient>>(
      '/patient',
      { q: query.trim(), v: 'default' }
    );
    return response.results;
  }

  async getPatientByUuid(uuid: string): Promise<OpenMRSPatient> {
    if (!uuid) throw new Error('Patient UUID is required');
    return openmrsClient.get<OpenMRSPatient>(`/patient/${uuid}`, { v: 'default' });
  }

  async generateOpenmrsId(): Promise<string> {
    const response = await openmrsClient.post<{ identifier: string }>(
      `/idgen/identifiersource/${IDGEN_SOURCE_UUID}/identifier`,
      { comment: 'Generated by CarePulse EMR service' }
    );
    if (!response.identifier) throw new Error('idgen returned no identifier');
    return response.identifier;
  }

  async createPatient(input: CreatePatientInput): Promise<OpenMRSPatient> {
    const openmrsId = await this.generateOpenmrsId();

    const payload: CreatePatientPayload = {
      identifiers: [
        {
          identifier:     openmrsId,
          identifierType: OPENMRS_ID_TYPE,
          location:       config.OPENMRS.LOCATION_UUID,
          preferred:      true,
        },
        {
          identifier:     input.identifier,
          identifierType: config.OPENMRS.IDENTIFIER_TYPE_UUID,
          location:       config.OPENMRS.LOCATION_UUID,
          preferred:      false,
        },
      ],
      person: {
        gender: input.gender,
        names: [
          {
            givenName:  input.givenName,
            familyName: input.familyName,
            preferred:  true,
          },
        ],
        ...(input.birthdate ? { birthdate: input.birthdate } : {}),
        ...(input.age       ? { age: input.age }             : {}),
      },
    };

    return openmrsClient.post<OpenMRSPatient>('/patient', payload);
  }
}

export const patientService = new PatientService();
